language: node_js
node_js:
  - '10'
script:
  - npm install
  - npm install express socket.io
  - npm start
cache:
  directories:
    - node_modules
notifications:
  email:
    on_success: never
    on_failure: always
